/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SpecialTerm;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Jacob Laurel
 */
public class PizzaShop extends javax.swing.JFrame {

    /**
     * Created by Jacob Laurel
     */
    public PizzaShop() {
        initComponents();
        
        ButtonGroup sz = new ButtonGroup();
	sz.add(jSizeSmall);
	sz.add(jSizeMedium);
        sz.add(jSizeLarge);
        sz.add(jSizeInvi);
        ButtonGroup tp = new ButtonGroup();
	tp.add(jTypeThin);
	tp.add(jTypeMedium);
        tp.add(jTypePan);
        tp.add(jTypeInvi);
        
        jTextArea.setText("\n\n\nProcess your order here:");
        
        jLabel2.setForeground(Color.WHITE);
        
        jSizeInvi.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSizeInvi = new javax.swing.JRadioButton();
        jTypeInvi = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTopping1 = new javax.swing.JCheckBox();
        jTopping2 = new javax.swing.JCheckBox();
        jTopping3 = new javax.swing.JCheckBox();
        jTopping4 = new javax.swing.JCheckBox();
        jTopping5 = new javax.swing.JCheckBox();
        jTopping6 = new javax.swing.JCheckBox();
        jTopping7 = new javax.swing.JCheckBox();
        jTopping8 = new javax.swing.JCheckBox();
        jTopping9 = new javax.swing.JCheckBox();
        jTopping10 = new javax.swing.JCheckBox();
        jTopping11 = new javax.swing.JCheckBox();
        jTopping12 = new javax.swing.JCheckBox();
        jTopping13 = new javax.swing.JCheckBox();
        jTopping14 = new javax.swing.JCheckBox();
        jTopping15 = new javax.swing.JCheckBox();
        jTopping16 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jReset = new javax.swing.JButton();
        jProcess = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSizeLarge = new javax.swing.JRadioButton();
        jSizeMedium = new javax.swing.JRadioButton();
        jSizeSmall = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTypePan = new javax.swing.JRadioButton();
        jTypeMedium = new javax.swing.JRadioButton();
        jTypeThin = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Style Pizza Shop");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel2.setText("Welcome to Home Style Pizza Shop");

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Toppings: ($1.50)");
        jLabel3.setToolTipText("");

        jTopping1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTopping1.setForeground(new java.awt.Color(0, 0, 0));
        jTopping1.setText("Anchovies");

        jTopping2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTopping2.setForeground(new java.awt.Color(0, 0, 0));
        jTopping2.setText("Artichokes");

        jTopping3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTopping3.setForeground(new java.awt.Color(0, 0, 0));
        jTopping3.setText("Bacon");

        jTopping4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTopping4.setForeground(new java.awt.Color(0, 0, 0));
        jTopping4.setText("Beef");

        jTopping5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTopping5.setForeground(new java.awt.Color(0, 0, 0));
        jTopping5.setText("Eggplant");

        jTopping6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTopping6.setForeground(new java.awt.Color(0, 0, 0));
        jTopping6.setText("Extra Cheese");

        jTopping7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTopping7.setForeground(new java.awt.Color(0, 0, 0));
        jTopping7.setText("Ham");

        jTopping8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTopping8.setForeground(new java.awt.Color(0, 0, 0));
        jTopping8.setText("Meatballs");

        jTopping9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTopping9.setForeground(new java.awt.Color(0, 0, 0));
        jTopping9.setText("Mushrooms");

        jTopping10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTopping10.setForeground(new java.awt.Color(0, 0, 0));
        jTopping10.setText("Onions");

        jTopping11.setForeground(new java.awt.Color(0, 0, 0));
        jTopping11.setText("Pepperoni");

        jTopping12.setForeground(new java.awt.Color(0, 0, 0));
        jTopping12.setText("Pineapple");

        jTopping13.setForeground(new java.awt.Color(0, 0, 0));
        jTopping13.setText("Salami");

        jTopping14.setForeground(new java.awt.Color(0, 0, 0));
        jTopping14.setText("Sausage");

        jTopping15.setForeground(new java.awt.Color(0, 0, 0));
        jTopping15.setText("Shrimp");

        jTopping16.setForeground(new java.awt.Color(0, 0, 0));
        jTopping16.setText("Spinach");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTopping8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTopping9)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTopping2)
                                .addComponent(jTopping5)
                                .addComponent(jTopping4)
                                .addComponent(jTopping3)
                                .addComponent(jTopping1)
                                .addComponent(jTopping6)
                                .addComponent(jTopping7))
                            .addGap(48, 48, 48)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTopping11)
                                .addComponent(jTopping10)
                                .addComponent(jTopping12)
                                .addComponent(jTopping13)
                                .addComponent(jTopping14)
                                .addComponent(jTopping15)
                                .addComponent(jTopping16))
                            .addGap(6, 6, 6))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTopping1)
                    .addComponent(jTopping9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTopping2)
                    .addComponent(jTopping10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTopping3)
                    .addComponent(jTopping11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTopping4)
                    .addComponent(jTopping12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTopping5)
                    .addComponent(jTopping13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTopping6)
                    .addComponent(jTopping14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTopping7)
                    .addComponent(jTopping15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTopping8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTopping16))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jTextArea.setRows(5);
        jTextArea.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea);

        jReset.setText("Reset Order");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jProcess.setText("Process Order");
        jProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProcessActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        jSizeLarge.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jSizeLarge.setForeground(new java.awt.Color(0, 0, 0));
        jSizeLarge.setText("Large          ($10.00)");

        jSizeMedium.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jSizeMedium.setForeground(new java.awt.Color(0, 0, 0));
        jSizeMedium.setText("Medium         ($8.50)");

        jSizeSmall.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jSizeSmall.setForeground(new java.awt.Color(0, 0, 0));
        jSizeSmall.setText("Small          ($6.50)");

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pizza Size:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSizeSmall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSizeMedium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSizeLarge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSizeSmall)
                .addGap(18, 18, 18)
                .addComponent(jSizeMedium)
                .addGap(18, 18, 18)
                .addComponent(jSizeLarge)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));

        jTypePan.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTypePan.setForeground(new java.awt.Color(0, 0, 0));
        jTypePan.setText("Pan Crust");

        jTypeMedium.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTypeMedium.setForeground(new java.awt.Color(0, 0, 0));
        jTypeMedium.setText("Medium Crust");

        jTypeThin.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTypeThin.setForeground(new java.awt.Color(0, 0, 0));
        jTypeThin.setText("Thin Crust");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Crust Type:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTypeThin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTypeMedium, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jTypePan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(67, 67, 67))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTypeThin)
                .addGap(18, 18, 18)
                .addComponent(jTypeMedium)
                .addGap(18, 18, 18)
                .addComponent(jTypePan)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
       jSizeSmall.setSelected(false);
       jSizeMedium.setSelected(false);
       jSizeLarge.setSelected(false);
       jSizeInvi.setSelected(true);
       
       jTopping1.setSelected(false);
       jTopping2.setSelected(false);
       jTopping3.setSelected(false);
       jTopping4.setSelected(false);
       jTopping5.setSelected(false);
       jTopping6.setSelected(false);
       jTopping7.setSelected(false);
       jTopping8.setSelected(false);
       jTopping9.setSelected(false);
       jTopping10.setSelected(false);
       jTopping11.setSelected(false);
       jTopping12.setSelected(false);
       jTopping13.setSelected(false);
       jTopping14.setSelected(false);
       jTopping15.setSelected(false);
       jTopping16.setSelected(false);
       
       jTypeThin.setSelected(false);
       jTypeMedium.setSelected(false);
       jTypePan.setSelected(false);
       jTypeInvi.setSelected(true);
       
       jTextArea.setText("\n\n\nProcess your order here:");
       
    }//GEN-LAST:event_jResetActionPerformed

    private void jProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProcessActionPerformed
       String Size = "";
       String Type = "";
       
       double SizePrice = 0;
       double ToppingPrice1 = 1.50;
       double ToppingPrice2 = 1.50;
       double ToppingPrice3 = 1.50;
       double ToppingPrice4 = 1.50;
       double ToppingPrice5 = 1.50;
       double ToppingPrice6 = 1.50;
       double ToppingPrice7 = 1.50;
       double ToppingPrice8 = 1.50;
       double ToppingPrice9 = 1.50;
       double ToppingPrice10 = 1.50;
       double ToppingPrice11 = 1.50;
       double ToppingPrice12 = 1.50;
       double ToppingPrice13 = 1.50;
       double ToppingPrice14 = 1.50;
       double ToppingPrice15 = 1.50;
       double ToppingPrice16 = 1.50;
       double TotalToppingPrice = 0;
       double TotalAmountDue = 0;
       
       // Size Radio Button
       if (jSizeSmall.isSelected()){
            Size = "Small ------------------------------ $";
            SizePrice = 6.50;
       }
       else if (jSizeMedium.isSelected()){
            Size = "Medium ----------------------------- $";
            SizePrice = 8.50;
       }
       else if (jSizeLarge.isSelected()){
            Size = "Large ------------------------------ $";
            SizePrice = 10.00;
       }
       else if (jSizeInvi.isSelected()){
            Size = "";
       }
       
       // Type Radio Button
       if (jTypeThin.isSelected()){
            Type = "Thin Crust";
       }
       else if (jTypeMedium.isSelected()){
            Type = "Medium Crust";
       }
       else if (jTypePan.isSelected()){
            Type = "Pan Crust";
       }
       else if (jTypeInvi.isSelected()){
            Type = "";
       }
        
       jTextArea.setText("HOME STYLE PIZZA SHOP");
       jTextArea.append("\nYour Order:");
       jTextArea.append("\n__________________________________________________");
       jTextArea.append("\n\n~ Pizza Size: " + Size + String.format("%.2f", + SizePrice));
       jTextArea.append("\n~ Toppings:");
       
       // Toppings Checkbox
       if (jTopping1.isSelected()){
            jTextArea.append("\n            Anchovies ---------------------------- $" + String.format("%.2f", + ToppingPrice1));
       }
       else
       {
           ToppingPrice1 = 0;
       }
       if (jTopping2.isSelected()){
            jTextArea.append("\n            Artichokes --------------------------- $" + String.format("%.2f", + ToppingPrice2));
       }
       else
       {
           ToppingPrice2 = 0;
       }
       if (jTopping3.isSelected()){
            jTextArea.append("\n            Bacon -------------------------------- $" + String.format("%.2f", + ToppingPrice3));
       }
       else
       {
           ToppingPrice3 = 0;
       }
       if (jTopping4.isSelected()){
            jTextArea.append("\n            Beef --------------------------------- $" + String.format("%.2f", + ToppingPrice4));
       }
       else
       {
           ToppingPrice4 = 0;
       }
       if (jTopping5.isSelected()){
            jTextArea.append("\n            Eggplant ----------------------------- $" + String.format("%.2f", + ToppingPrice5));
       }
       else
       {
           ToppingPrice5 = 0;
       }
       if (jTopping6.isSelected()){
            jTextArea.append("\n            Extra Cheese ------------------------- $" + String.format("%.2f", + ToppingPrice6));
       }
       else
       {
           ToppingPrice6 = 0;
       }
       if (jTopping7.isSelected()){
            jTextArea.append("\n            Ham ---------------------------------- $" + String.format("%.2f", + ToppingPrice7));
       }
       else
       {
           ToppingPrice7 = 0;
       }
       if (jTopping8.isSelected()){
            jTextArea.append("\n            Meatballs ---------------------------- $" + String.format("%.2f", + ToppingPrice8));
       }
       else
       {
           ToppingPrice8 = 0;
       }
       if (jTopping9.isSelected()){
            jTextArea.append("\n            Mushrooms ---------------------------- $" + String.format("%.2f", + ToppingPrice9));
       }
       else
       {
           ToppingPrice9 = 0;
       }
       if (jTopping10.isSelected()){
            jTextArea.append("\n            Onions ------------------------------- $" + String.format("%.2f", + ToppingPrice10));
       }
       else
       {
           ToppingPrice10 = 0;
       }
       if (jTopping11.isSelected()){
            jTextArea.append("\n            Pepperoni ---------------------------- $" + String.format("%.2f", + ToppingPrice11));
       }
       else
       {
           ToppingPrice11 = 0;
       }
       if (jTopping12.isSelected()){
            jTextArea.append("\n            Pineapple ---------------------------- $" + String.format("%.2f", + ToppingPrice12));
       }
       else
       {
           ToppingPrice12 = 0;
       }
       if (jTopping13.isSelected()){
            jTextArea.append("\n            Salami ------------------------------- $" + String.format("%.2f", + ToppingPrice13));
       }
       else
       {
           ToppingPrice13 = 0;
       }
       if (jTopping14.isSelected()){
            jTextArea.append("\n            Sausage ------------------------------ $" + String.format("%.2f", + ToppingPrice14));
       }
       else
       {
           ToppingPrice14 = 0;
       }
       if (jTopping15.isSelected()){
            jTextArea.append("\n            Shrimp ------------------------------- $" + String.format("%.2f", + ToppingPrice15));
       }
       else
       {
           ToppingPrice15 = 0;
       }
       if (jTopping16.isSelected()){
            jTextArea.append("\n            Spinach ------------------------------ $" + String.format("%.2f", + ToppingPrice16));
       }
       else
       {
           ToppingPrice16 = 0;
       }
       
       // Computation
       TotalToppingPrice = ToppingPrice1 + ToppingPrice2 + ToppingPrice3 + ToppingPrice4 + ToppingPrice5 + ToppingPrice6 + ToppingPrice7 + ToppingPrice8 + ToppingPrice9 + ToppingPrice10 + ToppingPrice11 + ToppingPrice12 + ToppingPrice13 + ToppingPrice14 + ToppingPrice15 + ToppingPrice16;
       TotalAmountDue = SizePrice + TotalToppingPrice;
       
       jTextArea.append("\n~ Crust Type: " + Type);
       jTextArea.append("\n__________________________________________________");
       jTextArea.append("\nTOTAL AMOUNT DUE: $" + String.format("%.2f", + TotalAmountDue));
       
    }//GEN-LAST:event_jProcessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PizzaShop().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jProcess;
    private javax.swing.JButton jReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jSizeInvi;
    private javax.swing.JRadioButton jSizeLarge;
    private javax.swing.JRadioButton jSizeMedium;
    private javax.swing.JRadioButton jSizeSmall;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JCheckBox jTopping1;
    private javax.swing.JCheckBox jTopping10;
    private javax.swing.JCheckBox jTopping11;
    private javax.swing.JCheckBox jTopping12;
    private javax.swing.JCheckBox jTopping13;
    private javax.swing.JCheckBox jTopping14;
    private javax.swing.JCheckBox jTopping15;
    private javax.swing.JCheckBox jTopping16;
    private javax.swing.JCheckBox jTopping2;
    private javax.swing.JCheckBox jTopping3;
    private javax.swing.JCheckBox jTopping4;
    private javax.swing.JCheckBox jTopping5;
    private javax.swing.JCheckBox jTopping6;
    private javax.swing.JCheckBox jTopping7;
    private javax.swing.JCheckBox jTopping8;
    private javax.swing.JCheckBox jTopping9;
    private javax.swing.JRadioButton jTypeInvi;
    private javax.swing.JRadioButton jTypeMedium;
    private javax.swing.JRadioButton jTypePan;
    private javax.swing.JRadioButton jTypeThin;
    // End of variables declaration//GEN-END:variables
}
